# This will curl your pkgbuild and update the pkgver

name: Create Pkgbuild

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Create PKGBUILD
        run:  |
          curl "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pulsemeeter" --silent > PKGBUILD
          sed -i "s/pkgver=.*/pkgver=$(python setup.py --version)/g" PKGBUILD

      # Runs a set of commands using the runners shell
      - name: Print PKGBUILD
        run: |
          cat PKGBUILD
